export default [
  {
    id: 1,
    picture: "https://source.unsplash.com/1600x900/?people",
    name: "Ridho Mustaqim",
    title: "Front End Developer",
    email: "ridho@gmail.com",
    password: "12345",
  },
  {
    id: 2,
    picture: "https://source.unsplash.com/1600x900/?people",
    name: "Ridho Mustaqim",
    title: "Front End Developer",
    email: "ridho@gmail.com",
    password: "12345",
  },
  {
    id: 3,
    picture: "https://source.unsplash.com/1600x900/?people",
    name: "Ridho Mustaqim",
    title: "Front End Developer",
    email: "ridho@gmail.com",
    password: "12345",
  },
  {
    id: 4,
    picture: "https://source.unsplash.com/1600x900/?people",
    name: "Ridho Mustaqim",
    title: "Front End Developer",
    email: "ridho@gmail.com",
    password: "12345",
  },
  {
    id: 5,
    picture: "https://source.unsplash.com/1600x900/?people",
    name: "Ridho Mustaqim",
    title: "Front End Developer",
    email: "ridho@gmail.com",
    password: "12345",
  },
];
